### PR TITLE
Rmvp 170

### PR DESCRIPTION
**Pull request by de-sage**
fixed the bug of the formal push by re implementing the post email form to align center of the screen

### CODE REVIEW

**Review by zanio — APPROVED** [review]
Well done

**Review by zanio — CHANGES_REQUESTED** [review]
Please see my comment

**Comment by zanio** [comment]
@de-sage Please see the comment i left your PR

**Comment by zanio** [comment]
Also please resolve the conflict from this branch

**Comment by de-sage** [comment]
ok am on it

**Comment by zanio** [comment]
Well done

**Pull request merged**
